import { useMemo, useState } from 'react';
import { KeyValueEditor } from './KeyValueEditor.jsx';
import styles from './RequestBuilder.module.css';
import { getDefaultHeadersPreview } from '../../utils/httpClient.js';

const HEADER_SUGGESTIONS = [
  'Content-Type',
  'Authorization',
  'Accept',
  'Cache-Control',
  'User-Agent',
  'X-API-Key',
  'Accept-Language',
  'X-Request-Id',
];

export function HeadersEditor({ request, rows, onChange }) {
  const [showAutoHeaders, setShowAutoHeaders] = useState(false);
  const defaultHeaders = useMemo(
    () => getDefaultHeadersPreview({ ...request, headers: rows }),
    [request, rows]
  );

  function hasHeaderByKey(entries, key) {
    const target = String(key || '').trim().toLowerCase();
    return entries.some((entry) => String(entry.key || '').trim().toLowerCase() === target);
  }

  function hasRowContent(entry = {}) {
    return Boolean((entry.key || '').trim() || (entry.value || '').trim() || (entry.description || '').trim());
  }

  function mergeAutoGeneratedRows(baseRows, defaults) {
    const next = baseRows.filter((entry) => entry.autoGenerated === true || hasRowContent(entry));
    defaults.forEach((header, index) => {
      if (!hasHeaderByKey(next, header.key)) {
        next.push({
          id: `hdr-auto-${Date.now()}-${index}`,
          key: header.key,
          value: header.value,
          enabled: true,
          autoGenerated: true,
        });
      }
    });
    return next;
  }

  function toggleAutoHeaders() {
    const nextValue = !showAutoHeaders;
    setShowAutoHeaders(nextValue);

    if (nextValue) {
      onChange(mergeAutoGeneratedRows(rows, defaultHeaders));
      return;
    }

    onChange(rows.filter((entry) => entry.autoGenerated !== true && hasRowContent(entry)));
  }

  return (
    <div className={styles.headersPane}>
      <section className={styles.autoHeadersBar} aria-label="Auto-generated header controls">
        <button type="button" className={styles.autoHeadersToggle} onClick={toggleAutoHeaders} aria-pressed={showAutoHeaders}>
          <svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            {showAutoHeaders ? (
              <>
                <path d="M2.2 12s3.4-6 9.8-6s9.8 6 9.8 6s-3.4 6-9.8 6s-9.8-6-9.8-6z" />
                <circle cx="12" cy="12" r="3.2" />
              </>
            ) : (
              <>
                <path d="M2.2 12s3.4-6 9.8-6c2.4 0 4.4.8 6 2" />
                <path d="M21.8 12s-3.4 6-9.8 6c-2.4 0-4.4-.8-6-2" />
                <path d="m3 3 18 18" />
              </>
            )}
          </svg>
          <span>{showAutoHeaders ? 'Hide auto-generated headers' : 'Show auto-generated headers'}</span>
        </button>
        <span className={styles.autoHeadersMeta}>
          {defaultHeaders.length} available
        </span>
      </section>

      <KeyValueEditor
        label="Header List"
        mode="headers"
        rows={rows}
        onChange={onChange}
        keySuggestions={HEADER_SUGGESTIONS}
        suppressDraftRow={showAutoHeaders}
      />
    </div>
  );
}
