const BODYLESS_METHODS = new Set(['GET', 'HEAD']);

function buildBody(request) {
  const bodyType = request.body?.type || 'none';

  if (BODYLESS_METHODS.has(request.method?.toUpperCase())) {
    return '';
  }

  if (bodyType === 'none') return '';

  if (bodyType === 'json') return request.body.raw || '';
  if (bodyType === 'raw') return request.body.raw || '';

  if (bodyType === 'x-www-form-urlencoded') {
    const params = new URLSearchParams();
    for (const entry of request.body.form || []) {
      if (entry.enabled !== false && entry.key) {
        params.append(entry.key, entry.value || '');
      }
    }
    return params.toString();
  }

  if (bodyType === 'form-data') {
    return JSON.stringify(
      (request.body.form || []).filter((entry) => entry.enabled !== false).map(({ key, value }) => ({ key, value }))
    );
  }

  return request.body.raw || '';
}

function hasHeader(headers = {}, key = '') {
  const target = key.toLowerCase();
  return Object.keys(headers).some((entry) => entry.toLowerCase() === target);
}

function getUserHeadersMap(request = {}) {
  return Object.fromEntries(
    (request.headers || [])
      .filter((entry) => entry.enabled !== false && entry.key && entry.autoGenerated !== true)
      .map((entry) => [entry.key, entry.value || ''])
  );
}

function getAutogeneratedHeaders(request, body) {
  const auto = {};
  const method = (request.method || 'GET').toUpperCase();
  const bodyType = request.body?.type || 'none';
  const hasBody = !BODYLESS_METHODS.has(method) && body !== undefined && body !== null && body !== '';

  if (!hasBody) {
    return auto;
  }

  if (bodyType === 'json') {
    auto['Content-Type'] = 'application/json';
  } else if (bodyType === 'x-www-form-urlencoded') {
    auto['Content-Type'] = 'application/x-www-form-urlencoded';
  } else if (bodyType === 'raw') {
    auto['Content-Type'] = 'text/plain';
  }

  return auto;
}

export function getDefaultHeadersPreview(request = {}) {
  const userHeaders = getUserHeadersMap(request);
  const body = buildBody(request);
  const autogenerated = getAutogeneratedHeaders(request, body);
  const defaults = [];

  if (!hasHeader(userHeaders, 'Accept')) {
    defaults.push({ key: 'Accept', value: '*/*' });
  }

  for (const [key, value] of Object.entries(autogenerated)) {
    if (!hasHeader(userHeaders, key)) {
      defaults.push({ key, value });
    }
  }

  return defaults;
}

export function buildProxyPayload(request, security = {}) {
  const userHeaders = getUserHeadersMap(request);
  const body = buildBody(request);
  const headers = { ...userHeaders };
  const defaults = getDefaultHeadersPreview(request);
  defaults.forEach(({ key, value }) => {
    headers[key] = value;
  });

  return {
    method: request.method,
    url: request.url,
    headers,
    body,
    security: {
      verifySsl: security.verifySsl !== false,
      useProxy: security.useProxy !== false,
      ...(typeof security.ca === 'string' && security.ca.trim() ? { ca: security.ca.trim() } : {}),
      ...(typeof security.cert === 'string' && security.cert.trim() ? { cert: security.cert.trim() } : {}),
      ...(typeof security.key === 'string' && security.key.trim() ? { key: security.key.trim() } : {}),
      ...(typeof security.passphrase === 'string' && security.passphrase ? { passphrase: security.passphrase } : {}),
    },
  };
}

export async function sendProxyRequest(request, endpoint = '/proxy', security = {}) {
  const payload = buildProxyPayload(request, security);
  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  const data = await response.json();

  if (!data.ok) {
    return {
      ...data,
      error: data.error || 'Request failed',
    };
  }

  return {
    status: data.status,
    statusText: data.statusText,
    headers: data.headers || {},
    body: data.body || '',
    time: data.time,
    size: data.size,
    error: null,
  };
}
